-- ============================================================
--  ZODPRO katalogi — 05-dimaxod-izolyatsiya-katyol
--  526 ta tovar. Narxlar dollarda.
--
--  Supabase -> SQL Editor -> New query -> to'liq nusxalang -> Run.
--  Qayta ishga tushirsangiz takrorlanmaydi (artikul bo'yicha yangilanadi).
-- ============================================================

create unique index if not exists hs_products_artikul_key
  on hs_products (artikul) where artikul <> '';

-- Brendlar katalog daraxtida tursin
insert into hs_categories (nomi, ota, tartib) values
  ('CLIMATE HOUSE', 'AVTOMATIKA', 10),
  ('DANFOSS', 'AVTOMATIKA', 20),
  ('Neptun', 'AVTOMATIKA', 30),
  ('Smartheat', 'AVTOMATIKA', 40),
  ('A.D.M', 'DIMAXOD', 10),
  ('COX GEELEN', 'DIMAXOD', 20),
  ('ENERGOFLEX', 'IZOLYATSIYA', 10),
  ('TONLOS', 'IZOLYATSIYA', 20),
  ('ALCAPLAST', 'SANTEXNIKA', 10)
on conflict (nomi, coalesce(ota, '')) do update set tartib = excluded.tartib, faol = true;


-- DIMAXOD / A.D.M  (84 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('ADM40.', 'Ati Di Mariani 1-108 X Dimoxodnaya truba iz nerj.stali d 80mm L-1000mm', 58.60, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM41.', 'Ati Di Mariani 1-28 X Dimoxodnaya truba iz nerj.stali d 80mm L-250mm', 21.49, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM42.', 'Ati Di Mariani 1-58 X Dimoxodnaya truba iz nerj.stali d 80mm L-500mm', 26.69, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM43.', 'Ati Di Mariani 10-8 AX Nakonechnik narujniy gorizontalniy iz nerj.stali d 80mm', 13.01, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM14.', 'Ati Di Mariani 2-4610PMF Koaksalnaya Poluotvod 45 C  ALU  60/100', 33.86, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM44.', 'Ati Di Mariani 2-48 XR Poluotvod 45S iz nerj.stali d 80mm', 32.55, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM1.', 'Ati Di Mariani 2-9610PMF Koaksalnaya otvod 90 C iz     ALU d 60/100', 41.68, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM45.', 'Ati Di Mariani 2-98 XR Otvod 90S iz nerj.stali d 80mm', 41.68, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM46.', 'Ati Di Mariani 3-8 TX Troynik 90S iz nerj.stali d 80mm', 53.39, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM47.', 'Ati Di Mariani 4-8 SX Truba vertik.so slivom dlya kondensata iz nerj.stali d 80mm', 36.45, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM48.', 'Ati Di Mariani 6-8 SX Nakonechnik narujniy vertikalniy iz nerj.stali d 80mm', 45.57, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM50.', 'Ati Di Mariani 8-68 XV Perexodnik vertikalniy iz nerj.stali 60M-80P', 45.57, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM49.', 'Ati Di Mariani 8-86 XV Perexodnik vertikalniy iz nerj.stali 80M-60P', 45.57, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM16.', 'Ati Di Mariani KKCC100 Truba Koaksalnaya gorizontalnaya s neylon.nakonech.iz ALU 60/100 L=850mm', 45.57, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM15.', 'Ati Di Mariani KKPC050 Truba Koaksalnaya iz ALU 60/100 L=500 mm', 48.17, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM55.', 'Ati Di Mariani W20-60F Uplotnitelnaya rezina dlya dimoxodnoy Gofratrubi iz PPR d 60mm', 1.56, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM54.', 'Ati Di Mariani W20-80 Uplotnitelnaya rezina dlya dimoxodnoy trubi iz PPR d 80mm', 1.95, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM2.', 'Ati Di Mariani W9-6FX Klipsa metal  dlya Gofratruba iz PPR d 60mm', 5.20, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM28.', 'Ati Di Mariani W9-8FX Klipsa metal  dlya Gofratruba iz PPR d 80mm', 11.72, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM29.', 'Ati Di Mariani W9-8RX Klipsa metal  dlya truba iz PPR d 80mm', 13.01, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM56.', 'Ati Di Mariani WB1-10110P Truba Dimoxodnaya iz PR d 110mm L=1000mm', 31.25, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM79.', 'Ati Di Mariani WB1-10200P Truba Dimoxodnaya iz PPR d 200mm L=1000mm', 54.69, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM3.', 'Ati Di Mariani WB1-106P Truba Dimoxodnaya  iz PR d 60mm L-1000mm', 16.92, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM30.', 'Ati Di Mariani WB1-108P Truba Dimoxodnaya  iz PR d 80mm L-1000mm', 18.24, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM57.', 'Ati Di Mariani WB1-20110P Truba Dimoxodnaya iz PR d 110mm L=2000mm', 55.99, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM80.', 'Ati Di Mariani WB1-20200P Truba Dimoxodnaya iz PR d 200mm L=2000mm', 91.14, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM4.', 'Ati Di Mariani WB1-206P Truba Dimoxodnaya  iz PR d 60mm L-2000mm', 28.64, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM31.', 'Ati Di Mariani WB1-208P Truba Dimoxodnaya  iz PR d 80mm L-2000mm', 33.86, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM5.', 'Ati Di Mariani WB1-26P Truba Dimoxodnaya  iz PR d 60mm L-250mm', 8.46, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM32.', 'Ati Di Mariani WB1-28P Truba Dimoxodnaya  iz PR d 80mm L-250mm', 9.76, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM58.', 'Ati Di Mariani WB1-5110P Truba Dimoxodnaya iz PR d 110mm L=500mm', 20.82, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM6.', 'Ati Di Mariani WB1-56P Truba Dimoxodnaya  iz PR d 60mm L-500mm', 10.42, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM33.', 'Ati Di Mariani WB1-58P Truba Dimoxodnaya  iz PR d 80mm L-500mm', 11.72, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM59.', 'Ati Di Mariani WB13-110PMF Troynik 90 S  d 110mm', 42.31, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM62.', 'Ati Di Mariani WB13-110PSO Troynik 90 S so slivom dlya kondensata iz PPR d 110mm', 47.52, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM51.', 'Ati Di Mariani WB13-60PMF Troynik 90 S  d 60mm', 18.24, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM61.', 'Ati Di Mariani WB13-80PMF Troynik 90 S  d 80mm', 24.74, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM60.', 'Ati Di Mariani WB16-110P  Slivnoy zaglushka dlya kondensata iz PR d 110mm', 28.00, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM63.', 'Ati Di Mariani WB16-60P  Slivnoy zaglushka dlya kondensata iz PR d 60mm', 13.01, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM64.', 'Ati Di Mariani WB16-80P  Slivnoy zaglushka dlya kondensata iz PR d 80mm', 14.33, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM7.', 'Ati Di Mariani WB2-36P Poluotvod 30 S iz PPR d 60mm', 11.06, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM34.', 'Ati Di Mariani WB2-38P Poluotvod 30 S iz PPR d 80mm', 13.01, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM65.', 'Ati Di Mariani WB2-4110P Poluotvod 45 S iz PPR d 110mm', 14.96, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM8.', 'Ati Di Mariani WB2-46P Poluotvod 45 S iz PPR d 60mm', 9.76, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM35.', 'Ati Di Mariani WB2-48P Poluotvod 45 S iz PPR d 80mm', 11.06, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM66.', 'Ati Di Mariani WB2-9110P Otvod 93 S iz PPR d 110mm', 15.62, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM81.', 'Ati Di Mariani WB2-9200P Otvod 90 S iz PPR d=200mm', 71.61, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM36.', 'Ati Di Mariani WB2-93PSC Otvod 90 S s krepejnim gaykay  PPR d 80mm', 18.24, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM9.', 'Ati Di Mariani WB2-96P Otvod 90 S iz PPR d 60mm', 11.06, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM52.', 'Ati Di Mariani WB2-96PIS Otvod 90 S c revizivey iz PPR d60mm', 26.05, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM10.', 'Ati Di Mariani WB2-96PSC Otvod 90 S s krepejnim gaykay  PPR d 60mm', 23.44, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM53.', 'Ati Di Mariani WB2-98PIS Otvod 90 S s revizivey iz PPR d 80mm', 31.25, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM17.', 'Ati Di Mariani WB3-88 I  Adaptor dlya kond.  Immergas 80/80', 14.96, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM67.', 'Ati Di Mariani WB8-1108PO Perexodnik vertikalniy iz PPR 110M-80P', 50.77, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM68.', 'Ati Di Mariani WB8-1110P  Perexodnik dlya vertikalnoy trubi [PPs] 0 100 M / 0 110', 39.06, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM69.', 'Ati Di Mariani WB8-65P Perexodnik vertikalniy iz PPR 60F-50M', 20.82, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM18.', 'Ati Di Mariani WBCA610 Truba Koaksalnaya gorizon. s antizamerzanie  iz PP/ALU  60/100 L=1000mm', 74.88, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM70.', 'Ati Di Mariani WBCR890 Poluotvod 45 S iz PPR d 80/125mm', 48.83, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM19.', 'Ati Di Mariani WBCUR61002  Koaksalnaya otvod 90C iz PP/ALU d-60-100 dlya VIESSMANN', 49.49, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM20.', 'Ati Di Mariani WBCUR61045  Koaksalniy poluotvod  45 S  iz PP/ALU d-60/100', 39.06, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM21.', 'Ati Di Mariani WBCUR61090  Koaksalnaya otvod 93C PP/ALU  d-60/100', 58.60, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM11.', 'Ati Di Mariani WBF60P Dimoxodnaya Gofratruba iz PP d 60mm L-50mm', 16.27, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM37.', 'Ati Di Mariani WBF80P Dimoxodnaya Gofratruba iz PR d 80mm L-50mm', 18.24, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM82.', 'Ati Di Mariani WBF80T Dimoxodnaya Teleskopicheskiy Gofratruba iz PPR d 80mm L-500mm', 13.08, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM22.', 'Ati Di Mariani WBPC610025 Truba Koaksalnaya iz PP/ALU d-60/100 L=250mm', 22.14, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM23.', 'Ati Di Mariani WBPC610050 Truba Koaksalnaya iz PP/ALU d-60/100 L=500mm', 33.86, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM24.', 'Ati Di Mariani WBPC610100 Truba Koaksalnaya iz PP/ALU d-60/100 L=1000mm', 45.57, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM25.', 'Ati Di Mariani WBPC610200 Truba Koaksalnaya iz PP/ALU d-60/100 L=2000mm', 54.69, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM71.', 'Ati Di Mariani WBPP61002  Koaksalnaya vertik.adaptor iz PP d-60/100  dlya VIESSMANN', 36.45, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM72.', 'Ati Di Mariani WBPP610025 Truba Koaksalnaya iz PP d-60/100 L -250mm', 15.62, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM26.', 'Ati Di Mariani WBPP61004  Adaptor vertikalniy dlya IMMERGAS kond. d-60/100     (s flyantsem)', 29.95, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM73.', 'Ati Di Mariani WBPP610050 Truba Koaksalnaya iz PP d-60/100 L -500mm', 24.09, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM74.', 'Ati Di Mariani WBPP610100 Truba Koaksalnaya iz PP d-60/100 L -1000mm', 33.86, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM83.', 'Ati Di Mariani WBPP610200 Truba Koaksalnaya iz PP d-60/100 L -2000mm', 45.57, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM75.', 'Ati Di Mariani WBPP61045   Koaksalnaya poluotvod 45 S d-60', 26.05, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM76.', 'Ati Di Mariani WBPZ805 Truba 500mm  S iz PPR d 80/125mm', 52.07, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM77.', 'Ati Di Mariani WBPZ810 Truba 1000mm  S iz PPR d 80/125mm', 72.92, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM12.', 'Ati Di Mariani WM45-60P Nakonechnik naruj/korot.dlya dimoxod.trubi iz PPR d-60 mm', 44.26, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM39.', 'Ati Di Mariani WM45-80P Nakonechnik naruj/korot.dlya dimoxod.trubi iz PPR d-80 mm', 44.26, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM27.', 'Ati Di Mariani WMSCV610 Koaksalniy kondensat sbornik vertik  PP/ALU', 52.07, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM84.', 'Ati Di Mariani WMTC610 Trubniy  nakonechnik nar.vertik.dlya dimoxod iz PP/ALU d-60/100  L=1300mm', 100.26, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM13.', 'Ati Di Mariani WN10-060  Nakonechnik vetrozashchitniy  d-60 mm', 10.42, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM38.', 'Ati Di Mariani WN10-080  Nakonechnik vetrozashchitniy  d-80 mm', 7.81, 'dona', 'DIMAXOD', 'A.D.M'),
  ('ADM78.', 'Ati Di Mariani WN10-100  Nakonechnik vetrozashchitniy  d-100 mm', 11.72, 'dona', 'DIMAXOD', 'A.D.M')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- DIMAXOD / COX GEELEN  (54 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('CREDAA601.', 'Cox Geelen dimoxodnaya gofratruba iz PP d 110mm L=25M', 35.62, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CXEDAK600.', 'Cox Geelen dimoxodnaya gofratruba iz PP d 110mm L=25M', 35.62, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BRERAA601.', 'Cox Geelen dimoxodnaya gofratruba iz PP d 80mm L=80M', 21.10, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CRFZAA601.', 'Cox Geelen Izgbnaya  Mufta dlya gofrotrubi iz PPR d110', 46.88, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BRFZAA601.', 'Cox Geelen Izgbnaya  Mufta dlya gofrotrubi iz PPR d80', 35.94, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKLNAA000.', 'Cox Geelen Kaskadniy dimoxod iz PPR d160-2x110mm', 546.88, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKFPAB600.', 'Cox Geelen Kaskadniy neobratniy klapon PPR d80', 132.81, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKHRAB600.', 'Cox Geelen Kaskadniy neobratniy klapon,vklyuchaya vodyanoy zamok PPR d80', 148.44, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKMTAB601.', 'Cox Geelen Klipsa  iz PPR d80mm', 7.02, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKANAA700.', 'Cox Geelen Kondentsat sbor Troynik Dimoxodnaya iz PPR d110mm', 93.75, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKARAA700.', 'Cox Geelen Kondentsat sbor Troynik Dimoxodnaya iz PPR d110mm', 42.19, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKARAA700.', 'Cox Geelen Kondentsat sbor Troynik Dimoxodnaya iz PPR d160mm', 171.88, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKANAA601.', 'Cox Geelen Kondentsat sbor Troynik Dimoxodnaya iz PPR d80mm', 45.31, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKAHAA700.', 'Cox Geelen Otvod   90 C iz PPR d110mm', 20.31, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKAHAA700.', 'Cox Geelen Otvod   90 C iz PPR d160mm', 66.40, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKAHAB601.', 'Cox Geelen Otvod  90 C iz PPR d80mm', 13.27, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKCNAA700.', 'Cox Geelen Otvod Reviziya  90 C iz PPR d110mm', 54.69, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKCNAA700.', 'Cox Geelen Otvod Reviziya  90 C iz PPR d160mm', 104.69, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKCNAA600.', 'Cox Geelen Otvod Reviziya  90 C iz PPR d80mm', 27.35, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKFEAA700.', 'Cox Geelen Perexod iz PPR d100/110mm', 39.06, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CLHXAA601.', 'Cox Geelen Perexod iz PPR d100/110mm', 65.62, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKENAA700.', 'Cox Geelen Perexod iz PPR d110/160mm', 174.38, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKFHAA700.', 'Cox Geelen Perexod iz PPR d150/160mm', 125.00, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKASAAB601.', 'Cox Geelen Perexod iz PPR d60/80mm', 34.38, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKHEAA700.', 'Cox Geelen Perexod iz PPR d80/110mm', 54.69, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKDBAA700.', 'Cox Geelen Poluotvod 15 C iz PPR d110mm', 25.00, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKDBAB601.', 'Cox Geelen Poluotvod 15 C iz PPR d80mm', 18.75, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKDAAA700.', 'Cox Geelen Poluotvod 30 C iz PPR d110mm', 25.00, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKDAAA700.', 'Cox Geelen Poluotvod 30 C iz PPR d160mm', 129.53, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKDAAB601.', 'Cox Geelen Poluotvod 30 C iz PPR d80mm', 20.31, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKAJAB700.', 'Cox Geelen Poluotvod 45 C iz PPR d110mm', 14.06, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKAJAA700.', 'Cox Geelen Poluotvod 45 C iz PPR d160mm', 64.38, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKAJAB601.', 'Cox Geelen Poluotvod 45 C iz PPR d80mm', 12.50, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKAKAB700.', 'Cox Geelen Razdvijnaya Truba Dimoxodnaya iz PPR d110mm', 20.31, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKAKAB601.', 'Cox Geelen Razdvijnaya Truba Dimoxodnaya iz PPR d80mm', 14.85, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BEAHAA601.', 'Cox Geelen RGE//BDCLAA601 P/A MDV 80/125 Dimoxod kondensatsionnogo kotlu', 218.75, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('165110.', 'Cox Geelen Shapka Nakonechnik naruj/korot,dlya dimoxod, d-110mm', 60.94, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('165150.', 'Cox Geelen Shapka Nakonechnik naruj/korot,dlya dimoxod, d-160mm', 109.38, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('165080.', 'Cox Geelen Shapka Nakonechnik naruj/korot,dlya dimoxod, d-80mm', 56.25, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('0212AA000.', 'Cox Geelen Smazka  30g', 7.02, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CRFTAA601.', 'Cox Geelen Soedinitelnaya Mufta iz PPR d110', 64.06, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BRFTAA601.', 'Cox Geelen Soedinitelnaya Mufta iz PPR d80', 59.38, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKALAA601.', 'Cox Geelen Troynik 90 C iz PPR d80mm', 57.81, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKAMAA700.', 'Cox Geelen Troynik reviziya  90 C iz PPR d160mm', 122.34, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKABAB700.', 'Cox Geelen Truba Dimoxodnaya iz PPR d110mm L-1000mm', 26.56, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKAAAA700.', 'Cox Geelen Truba Dimoxodnaya iz PPR d110mm L-2000mm', 62.50, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('CKACAB700.', 'Cox Geelen Truba Dimoxodnaya iz PPR d110mm L-500mm', 15.62, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKABAA700.', 'Cox Geelen Truba Dimoxodnaya iz PPR d160mm L-1000mm', 95.31, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('DKACAA700.', 'Cox Geelen Truba Dimoxodnaya iz PPR d160mm L-500mm', 64.85, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKABAB601.', 'Cox Geelen Truba Dimoxodnaya iz PPR d80mm L-1000mm', 19.52, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKAAAB601.', 'Cox Geelen Truba Dimoxodnaya iz PPR d80mm L-2000mm', 39.06, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKAAAC601.', 'Cox Geelen Truba Dimoxodnaya iz PPR d80mm L-2000mm', 39.06, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKADAB601.', 'Cox Geelen Truba Dimoxodnaya iz PPR d80mm L-250mm', 9.56, 'dona', 'DIMAXOD', 'COX GEELEN'),
  ('BKACAB601.', 'Cox Geelen Truba Dimoxodnaya iz PPR d80mm L-500mm', 13.27, 'dona', 'DIMAXOD', 'COX GEELEN')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- IZOLYATSIYA / ENERGOFLEX  (101 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('EN115.', 'Alyuminieviy skotch 100/50m', 7.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN116.', 'Alyuminieviy skotch 50/50m', 6.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN55.', 'Armofleks 9mm', 12.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN92.', 'Bur 8', 1.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN114.', 'Darojnaya setka 20x20', 15.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN113.', 'Darojnaya setka 5x5', 14.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN63.', 'Demfernaya lenta (1 metr)', 0.54, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN70.', 'Fiksator izgiba trubi 14-18mm (Polsha)', 0.89, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN80.', 'Fiksator izgiba trubi 14mm-18mm LiveLLO Beliy', 0.71, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN79.', 'Fiksator izgiba trubi 14mm-18mm LiveLLO Cherniy', 0.71, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN81.', 'Fiksator izgiba trubi 14mm-18mm LiveLLO Krasniy', 0.71, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN82.', 'Fiksator izgiba trubi 14mm-18mm LiveLLO Siniy', 0.71, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN64.1', 'Ftulka dlya kollektora', 0.67, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN78.', 'Izorol folga', 0.96, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN74.', 'Kalibrator valtsevatel dlya trub 16-20-26mm (Polsha)', 11.61, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN71.', 'Kalibrator valtsevatel dlya trub 16mm (Polsha)', 12.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN72.', 'Kalibrator valtsevatel dlya trub 20mm (Polsha)', 17.86, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN73.', 'Kalibrator valtsevatel dlya trub 32mm (Polsha)', 17.86, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN94.', 'Konsol 1000mm', 18.30, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN95.', 'Konsol 1500mm', 13.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN96.', 'Konsol 2000mm', 22.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN90.', 'Konsol 300mm', 4.46, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN93.', 'Konsol 500mm', 12.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN77.', 'Kreplenie dlya trub dvoynoy napolniy kryuk 100mm (Polsha)', 0.71, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN75.', 'Kreplenie dlya trub dvoynoy napolniy kryuk 48mm (Polsha)', 0.33, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN76.', 'Kreplenie dlya trub dvoynoy napolniy kryuk 77mm (Polsha)', 0.45, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN57.', 'Mat dlya TP (1sht=0.96m2)', 9.82, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN42.', 'Misot-flex ST-TB 9*102 (trubchataya izolyatsiya standartnaya)', 5.54, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN43.', 'Misot-flex ST-TB 9*114 (trubchataya izolyatsiya standartnaya)', 5.89, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN32.', 'Misot-flex ST-TB 9*15 (trubchataya izolyatsiya standartnaya)', 0.71, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN33.', 'Misot-flex ST-TB 9*18 (trubchataya izolyatsiya standartnaya)', 0.82, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN34.', 'Misot-flex ST-TB 9*22 (trubchataya izolyatsiya standartnaya)', 0.86, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN35.', 'Misot-flex ST-TB 9*28 (trubchataya izolyatsiya standartnaya)', 1.04, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN36.', 'Misot-flex ST-TB 9*35 (trubchataya izolyatsiya standartnaya)', 1.21, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN37.', 'Misot-flex ST-TB 9*42 (trubchataya izolyatsiya standartnaya)', 1.39, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN38.', 'Misot-flex ST-TB 9*48 (trubchataya izolyatsiya standartnaya)', 1.91, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN39.', 'Misot-flex ST-TB 9*54 (trubchataya izolyatsiya standartnaya)', 2.14, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN39.1', 'Misot-flex ST-TB 9*60 (trubchataya izolyatsiya standartnaya)', 2.42, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN40.', 'Misot-flex ST-TB 9*76 (trubchataya izolyatsiya standartnaya)', 3.11, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN41.', 'Misot-flex ST-TB 9*89 (trubchataya izolyatsiya standartnaya)', 3.75, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN99.', 'Montajnaya shina 1000 MM', 12.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN68.', 'Parashut', 0.07, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN69.1', 'Parashyut dyubel', 0.10, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN69.', 'Parashyut, shayba dlya krepleniya penoplasta', 0.04, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN75.1', 'Pena dlya penopleksa', 13.38, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN84.', 'Perfolenta', 8.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN83.', 'Plastikovaya knopka LiveLLO Krasniy (karobka 300sht)', 3.57, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN65.', 'Razmativatel dlya trub (Polsha)', 205.36, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN97.', 'Shpilka 8', 1.30, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN61.', 'Sintifon 3mm 50m', 0.39, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN62.', 'Sintifon 5mm 50m', 0.57, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN66.', 'Skoba (China)', 0.04, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN66.1', 'Skoba (Italy)', 0.05, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN67.', 'Skoba (UZB)', 0.04, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('Skotch', 'Skotch', 5.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN151.', 'Steklovata s folgoy, rulonnaya 15m2', 55.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('Stp', 'STP Shumoizolyatsiya', 5.38, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN64.', 'Taker dlya kassetnix skob (Polsha)', 178.58, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN58.', 'TerraPlex 2sm (shtk)', 1.39, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN59.', 'TerraPlex 3sm (shtk)', 2.14, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN60.', 'TerraPlex 5sm (shtk)', 3.49, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN20.', 'Trubka ENERGOFLEX SUPER PROTECT K 15/4-11', 0.41, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN10.1', 'Trubka ENERGOFLEX SUPER PROTECT K 15/6-2', 0.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN05.', 'Trubka ENERGOFLEX SUPER PROTECT K 15/9-2', 0.75, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN21.', 'Trubka ENERGOFLEX SUPER PROTECT K 18/4-11', 0.46, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN01.', 'Trubka ENERGOFLEX SUPER PROTECT K 18/6-2', 0.57, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN22.', 'Trubka ENERGOFLEX SUPER PROTECT K 22/4-11', 0.49, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN02.', 'Trubka ENERGOFLEX SUPER PROTECT K 22/6-2', 0.64, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN06.', 'Trubka ENERGOFLEX SUPER PROTECT K 22/9-2', 0.86, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN23.', 'Trubka ENERGOFLEX SUPER PROTECT K 28/4-11', 0.61, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN03.', 'Trubka ENERGOFLEX SUPER PROTECT K 28/6-2', 0.80, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN07.', 'Trubka ENERGOFLEX SUPER PROTECT K 28/9-2', 1.11, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN04.', 'Trubka ENERGOFLEX SUPER PROTECT K 35/6-2', 1.05, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN08.', 'Trubka ENERGOFLEX SUPER PROTECT K 35/9-2', 1.39, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN09.', 'Trubka ENERGOFLEX SUPER PROTECT K 42/9-3', 1.75, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN24.', 'Trubka ENERGOFLEX SUPER PROTECT S 15/4-11', 0.41, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN10.', 'Trubka ENERGOFLEX SUPER PROTECT S 15/6-2', 0.50, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN15.', 'Trubka ENERGOFLEX SUPER PROTECT S 15/9-2', 0.75, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN25.', 'Trubka ENERGOFLEX SUPER PROTECT S 18/4-11', 0.46, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN11.', 'Trubka ENERGOFLEX SUPER PROTECT S 18/6-2', 0.57, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN16.', 'Trubka ENERGOFLEX SUPER PROTECT S 18/9-2', 0.76, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN26.', 'Trubka ENERGOFLEX SUPER PROTECT S 22/4-11', 0.49, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN12.', 'Trubka ENERGOFLEX SUPER PROTECT S 22/6-2', 0.64, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN17.', 'Trubka ENERGOFLEX SUPER PROTECT S 22/9-2', 0.86, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN27.', 'Trubka ENERGOFLEX SUPER PROTECT S 28/4-11', 0.61, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN13.', 'Trubka ENERGOFLEX SUPER PROTECT S 28/6-2', 0.80, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN28.', 'Trubka ENERGOFLEX SUPER PROTECT S 35/4-11', 0.79, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN14.', 'Trubka ENERGOFLEX SUPER PROTECT S 35/6-2', 1.05, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN18.', 'Trubka ENERGOFLEX SUPER PROTECT S 35/9-2', 1.39, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN19.', 'Trubka ENERGOFLEX SUPER PROTECT S 42/9-3', 1.75, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN100.', 'XOMUT METALICHESKIY  (20) 1/2', 0.45, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN108.', 'XOMUT METALICHESKIY (110) 4''', 1.51, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN109.', 'XOMUT METALICHESKIY (160) 5''', 2.00, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN101.', 'XOMUT METALICHESKIY (25) 3/4', 0.49, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN102.', 'XOMUT METALICHESKIY (32) 1''', 0.57, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN103.', 'XOMUT METALICHESKIY (40) 1,1/4', 0.72, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN104.', 'XOMUT METALICHESKIY (50) 1,1/2', 0.64, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN105.', 'XOMUT METALICHESKIY (63) 2''', 0.70, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN106.', 'XOMUT METALICHESKIY (75) 2,1/2', 1.21, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN107.', 'XOMUT METALICHESKIY (90) 3''', 1.39, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX'),
  ('EN56.', 'Zajim 3.6/500', 5.17, 'dona', 'IZOLYATSIYA', 'ENERGOFLEX')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- IZOLYATSIYA / TONLOS  (2 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('Tonlos 2', 'Tonlos PIPE', 56.50, 'dona', 'IZOLYATSIYA', 'TONLOS'),
  ('Tonlos 1', 'Tonlos pipe pro', 106.00, 'dona', 'IZOLYATSIYA', 'TONLOS')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- KATYOL  (99 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('3308020.', 'Aksesuar dlya kotlov (3308020 FEET FOR BACD)', 25.00, 'dona', 'KATYOL', null),
  ('3318188.', 'Aksesuar dlya kotlov (COAXICIAL PIPE 1M CONDENSATION 3318188)', 47.50, 'dona', 'KATYOL', null),
  ('Buderus 10', 'BUDERUS Boyler kosvennogo nagreva SU 200/5 W', 1812.50, 'dona', 'KATYOL', null),
  ('Buderus 11', 'BUDERUS Boyler kosvennogo nagreva SU 300/5 W', 2312.50, 'dona', 'KATYOL', null),
  ('Buderus 4', 'BUDERUS Logamax plus GB122I 24 kv Nastenniy dvuhkont kondens. gazoviy kotel', 1562.50, 'dona', 'KATYOL', null),
  ('Buderus 5', 'BUDERUS Logamax plus GB172-35H Nastenniy kondens. gazoviy kotel', 2375.00, 'dona', 'KATYOL', null),
  ('Buderus 6', 'BUDERUS Logamax plus GB172I-42H Nastenniy kondens. gazoviy kotel', 2562.50, 'dona', 'KATYOL', null),
  ('Buderus 8', 'BUDERUS Logamax plus GB272-100H Nastenniy kondens. gazoviy kotel', 5812.50, 'dona', 'KATYOL', null),
  ('Buderus 9', 'BUDERUS Logamax plus GB272-150H Nastenniy kondens. gazoviy kotel', 7000.00, 'dona', 'KATYOL', null),
  ('Buderus 7', 'BUDERUS Logamax plus GB272-70H Nastenniy kondens. gazoviy kotel', 4750.00, 'dona', 'KATYOL', null),
  ('Buderus 2', 'BUDERUS LOGAMAX U072-24 K Nastenniy dvuhkont. gazoviy kotel', 1062.50, 'dona', 'KATYOL', null),
  ('Buderus 1', 'BUDERUS LOGAMAX U072-24 Nastenniy odnokont. gazoviy kotel', 1062.50, 'dona', 'KATYOL', null),
  ('Buderus 3', 'BUDERUS Logamax U072-35 Nastenniy odnokont. gazoviy kotel', 1400.00, 'dona', 'KATYOL', null),
  ('3201174-6.', 'COAXIAL PIPE 1M', 62.50, 'dona', 'KATYOL', null),
  ('3318000-1.', 'COAXIAL PIPE 1M (Dlya kondits.) 3318073', 62.50, 'dona', 'KATYOL', null),
  ('WKD5315000000/RU.', 'Combi boiler Kociol Minimax Elegance Turbo 35kW GCO-DP-21-03 dvux. kontur', 1500.00, 'dona', 'KATYOL', null),
  ('90160560-A.', 'Dimoxod dlya kondensatsionnix kotlov', 62.50, 'dona', 'KATYOL', null),
  ('WKJ 5141 000000/UA1W.', 'ECOCONDENS CRYSTAL 100', 6875.00, 'dona', 'KATYOL', null),
  ('WKJ 5025000001/UA.', 'ECOCONDENS CRYSTAL PLUS 50 Kondensat odno. kontur 50kv', 3250.00, 'dona', 'KATYOL', null),
  ('GCCX6B0A.', 'Ferroli BLUEHELIX SIGMA 24C', 1125.00, 'dona', 'KATYOL', null),
  ('GCCX8B0A.', 'Ferroli BLUEHELIX SIGMA 28C', 1250.00, 'dona', 'KATYOL', null),
  ('GCCF8F0A.', 'Ferroli BLUEHELIX SIGMA 28H', 1250.00, 'dona', 'KATYOL', null),
  ('GCCX9B0A.', 'Ferroli BLUEHELIX SIGMA 34C', 1312.50, 'dona', 'KATYOL', null),
  ('GCCF9F0A.', 'Ferroli BLUEHELIX SIGMA 34H', 1312.50, 'dona', 'KATYOL', null),
  ('GCKG2KYA.', 'Ferroli FORTUNA F 13 2x', 625.00, 'dona', 'KATYOL', null),
  ('GCKG6KYA.', 'Ferroli FORTUNA F 24 2x', 650.00, 'dona', 'KATYOL', null),
  ('GCKG8KYA.', 'Ferroli FORTUNA F 32 2x', 750.00, 'dona', 'KATYOL', null),
  ('GCKGAKYA.', 'Ferroli FORTUNA F 40 2x', 875.00, 'dona', 'KATYOL', null),
  ('GCAY6KYA.', 'Ferroli FORTUNA HF 24 1x', 650.00, 'dona', 'KATYOL', null),
  ('GCAY8KYA.', 'Ferroli FORTUNA HF 32 1x', 750.00, 'dona', 'KATYOL', null),
  ('GCAYAKYA.', 'Ferroli FORTUNA HF 40 1x', 875.00, 'dona', 'KATYOL', null),
  ('GCFO604A.', 'Ferroli TOR 24 Kotyol Elektricheskiy', 1062.50, 'dona', 'KATYOL', null),
  ('GCEO10EA.', 'Ferroli TOR 9 Kotyol Elektricheskiy', 875.00, 'dona', 'KATYOL', null),
  ('Lambo 24 2x.', 'LAMBORGHINI  Nasten kotli Dvux BORUI  F 24', 680.55, 'dona', 'KATYOL', null),
  ('Lambo 32 2x.', 'LAMBORGHINI  Nasten kotli Dvux BORUI  F 32', 763.89, 'dona', 'KATYOL', null),
  ('Lambo 40 2x.', 'LAMBORGHINI  Nasten kotli Dvux BORUI  F 40', 902.77, 'dona', 'KATYOL', null),
  ('Lambo 24 1x.', 'LAMBORGHINI  Nasten kotli Odno  BORUI  24', 625.00, 'dona', 'KATYOL', null),
  ('Lambo 32 1x.', 'LAMBORGHINI  Nasten kotli Odno  BORUI  32', 763.89, 'dona', 'KATYOL', null),
  ('Lambo 40 1x.', 'LAMBORGHINI  Nasten kotli Odno  BORUI  40', 902.77, 'dona', 'KATYOL', null),
  ('90160540.', 'Nabor koaksalnogo dimoxoda d60/100', 62.50, 'dona', 'KATYOL', null),
  ('WKJ5501000000/EU2T', 'SYSTEM BOILER EURO COMFORT 35 1x kontur kondetsionniy', 1875.00, 'dona', 'KATYOL', null),
  ('WKJ2025000000/RU.', 'SYSTEM BOILER UNICO 24 ELEGANCE odno kontur 24kv otkritiy kamera', 875.00, 'dona', 'KATYOL', null),
  ('T 9000 0135 00.', 'TERMET DIMOXOD 60/100 L -1000 mm (obichniy) 701348', 50.00, 'dona', 'KATYOL', null),
  ('T 9000013700.', 'TERMET DIMOXOD 60/100 L-1000mm (Kondensatsionniy) 700246', 50.00, 'dona', 'KATYOL', null),
  ('TPP9901000000/PL.', 'TERMET Teplovoy nasos Heat Gold 12 DC', 3875.00, 'dona', 'KATYOL', null),
  ('TPP9902000000/PL.', 'TERMET Teplovoy nasos Heat Gold 15 DC', 5750.00, 'dona', 'KATYOL', null),
  ('TPP9903000000/PL.', 'TERMET Teplovoy nasos Heat Gold 18 DC', 6500.00, 'dona', 'KATYOL', null),
  ('TPP9900000000/PL.', 'TERMET Teplovoy nasos Heat Gold 9 DC', 3125.00, 'dona', 'KATYOL', null),
  ('WKJ2065000000/NE', 'UNICO 24 ELEGANCE TERBO GCO-24-01 Одно контур 24кв', 1000.00, 'dona', 'KATYOL', null),
  ('Vaillant 1.', 'VAILLANT -  Kosvenniy Boyler  120', 1041.66, 'dona', 'KATYOL', null),
  ('Vaillant 2.', 'VAILLANT -  Kosvenniy Boyler 150', 1180.55, 'dona', 'KATYOL', null),
  ('Vaillant 14.', 'Vaillant Gruppa bistrogo montaja bez nasosa dlya radiatora', 375.00, 'dona', 'KATYOL', null),
  ('Vaillant 13.', 'Vaillant Gruppa bistrogo montaja s nasosam dlya Tep,pol', 777.77, 'dona', 'KATYOL', null),
  ('Vaillant 22.', 'Vaillant kaskadnaya plata VR32/3', 152.77, 'dona', 'KATYOL', null),
  ('Vaillant 16.', 'Vaillant Modul VR 70', 416.66, 'dona', 'KATYOL', null),
  ('Vaillant 17.', 'Vaillant Modul VR 71', 541.66, 'dona', 'KATYOL', null),
  ('Vaillant 18.', 'Vaillant Modul VR 92', 263.89, 'dona', 'KATYOL', null),
  ('Vaillant 15.', 'VAILLANT myVAILLANT connect VR940', 236.11, 'dona', 'KATYOL', null),
  ('Vaillant 5.', 'Vaillant Nastenniy Kondensatsionniy dvux,kontr kotel VUW 26CS ( 24 KWT', 2326.39, 'dona', 'KATYOL', null),
  ('Vaillant 6.', 'Vaillant Nastenniy Kondensatsionniy dvux,kontr kotel VUW 36CS ( 35 KWT', 2479.16, 'dona', 'KATYOL', null),
  ('Vaillant 7.', 'Vaillant Nastenniy Kondensatsionniy dvux,kontr kotel VUW 40CS ( 40 KWT', 2638.89, 'dona', 'KATYOL', null),
  ('Vaillant 23.', 'Vaillant Nastenniy Kondensatsionniy odno,kontr kotel 100 KWT   (Germany)', 6450.00, 'dona', 'KATYOL', null),
  ('Vaillant 3.', 'Vaillant Nastenniy Kondensatsionniy odno,kontr kotel VU 25CS  24 KWT  (Germany)', 2291.66, 'dona', 'KATYOL', null),
  ('Vaillant 4.', 'Vaillant Nastenniy Kondensatsionniy odno,kontr kotel VU 35 CS/1-5 35 KWT   (Germany)', 2430.55, 'dona', 'KATYOL', null),
  ('Vaillant 8.', 'Vaillant Nastenniy Kondensatsionniy odno,kontr kotel VU 486 50 KWT   (Germany)', 3472.22, 'dona', 'KATYOL', null),
  ('Vaillant 9.', 'Vaillant Nastenniy Kondensatsionniy odno,kontr kotel VU 656 65 KWT   (Germany)', 4652.77, 'dona', 'KATYOL', null),
  ('Vaillant 10.', 'Vaillant Raspredelitelniy kollektor vix-2', 402.78, 'dona', 'KATYOL', null),
  ('Vaillant 11.', 'Vaillant Raspredelitelniy kollektor vix-3', 472.22, 'dona', 'KATYOL', null),
  ('Vaillant 21.', 'Vaillant sensoHOME VRT380', 222.22, 'dona', 'KATYOL', null),
  ('Vaillant 12.', 'Vaillant Sensor GVS dlya boylera', 41.66, 'dona', 'KATYOL', null),
  ('Vaillant 19.', 'Vaillant SensorCOMFORT VRC 720', 375.00, 'dona', 'KATYOL', null),
  ('Vaillant 20.', 'Vaillant VR693 ulichniy datchik', 55.55, 'dona', 'KATYOL', null),
  ('Viessmann dimoxod', 'Viessman dimoxod dlya atmosferniy kotlov', 65.00, 'dona', 'KATYOL', null),
  ('Viessmann datchik .', 'Viessmann Datchik boylera original', 125.00, 'dona', 'KATYOL', null),
  ('7373237.', 'Viessmann Komplekt podkl. vnesh. stene D=60/100 PPs dlya Vitodens (otvod i truba)', 222.22, 'dona', 'KATYOL', null),
  ('7373338.', 'Viessmann Perexodnik', 37.50, 'dona', 'KATYOL', null),
  ('Vitodens50 25 1x.', 'Viessmann Vitodens 050-W 25 kVt Nastenniy kondensatsionniy 1-konturniy kotel', 1666.66, 'dona', 'KATYOL', null),
  ('Vitodens50 25 2x.', 'Viessmann Vitodens 050-W 25 kVt Nastenniy kondensatsionniy 2-konturniy kotel', 1736.11, 'dona', 'KATYOL', null),
  ('Vitodens50 32 2x.', 'Viessmann Vitodens 050-W 32 kVt Nastenniy kondensatsionniy 2-konturniy kotel', 1805.55, 'dona', 'KATYOL', null),
  ('Vitodens100 25 1x.', 'Viessmann Vitodens 100-W 25 kVt Nastenniy kondensatsionniy 1-konturniy kotel', 2013.89, 'dona', 'KATYOL', null),
  ('Vitodens100 25 2x.', 'Viessmann Vitodens 100-W 25 kVt Nastenniy kondensatsionniy 2-konturniy kotel', 2083.34, 'dona', 'KATYOL', null),
  ('Vitodens100 32 1x.', 'Viessmann Vitodens 100-W 32 kVt Nastenniy kondensatsionniy 1-konturniy kotel', 2152.78, 'dona', 'KATYOL', null),
  ('Vitodens100 32 2x.', 'Viessmann Vitodens 100-W 32 kVt Nastenniy kondensatsionniy 2-konturniy kotel', 2166.66, 'dona', 'KATYOL', null),
  ('Vitodens 111 25 2x.', 'Viessmann Vitodens 111W 25 kVt Nastenniy kondensatsionniy 2-konturniy kotel', 2569.45, 'dona', 'KATYOL', null),
  ('Vitodens 111 32 2x.', 'Viessmann Vitodens 111W 32 kVt Nastenniy kondensatsionniy 2-konturniy kotel', 2638.89, 'dona', 'KATYOL', null),
  ('7571693.', 'Viessmann Vitopend 24 kW A1HBU umlauf 1-konturniy kotel', 1027.77, 'dona', 'KATYOL', null),
  ('7571694.', 'Viessmann Vitopend 24 kW A1JB kombi 2-konturniy kotel', 1027.77, 'dona', 'KATYOL', null),
  ('7571695.', 'Viessmann Vitopend 30 kW A1HBU umlauf 1-konturniy kotel', 1138.89, 'dona', 'KATYOL', null),
  ('7571697.', 'Viessmann Vitopend 34 kW A1HBU umlauf 1-konturniy kotel', 1236.11, 'dona', 'KATYOL', null),
  ('7720264.', 'Viessmann Vitotron 100 24 kVt (3 phase) VLN3 Constant temp elektricheskiy kotel', 1250.00, 'dona', 'KATYOL', null),
  ('7720263.', 'Viessmann Vitotron 100 8 kVt (1 phase) VLN3 Constant temp elektricheskiy kotel', 1250.00, 'dona', 'KATYOL', null),
  ('3314249.', 'WALL HUNG BOILER MIRA ADVANCE SYSTEM D2 25', 2000.00, 'dona', 'KATYOL', null),
  ('3314250.', 'WALL HUNG BOILER MIRA ADVANCE SYSTEM D2 35', 2125.00, 'dona', 'KATYOL', null),
  ('3581096.', 'WALL HUNG BOILER TALIA SYSTEM GREEN 100 HP', 7000.00, 'dona', 'KATYOL', null),
  ('3581426.', 'WALL HUNG BOILER TALIA SYSTEM GREEN 150 HP', 8250.00, 'dona', 'KATYOL', null),
  ('3581421.', 'WALL HUNG BOILER TALIA SYSTEM GREEN 45 HP', 4625.00, 'dona', 'KATYOL', null),
  ('3581422.', 'WALL HUNG BOILER TALIA SYSTEM GREEN 65 HP', 5375.00, 'dona', 'KATYOL', null),
  ('3581423.', 'WALL HUNG BOILER TALIA SYSTEM GREEN 85 HP', 6125.00, 'dona', 'KATYOL', null),
  ('WGE3228000000/NE7K.', 'Water heater TERMAQ ELECTRONIC PRO GE-19-02 Gaz kalonka', 562.50, 'dona', 'KATYOL', null)
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- SANTEXNIKA / ALCAPLAST  (99 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('AGV3.', 'AGV3 - Universalnie livneotvodi - Alcadrain s.r.o', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('AM101/1120.', 'Alcaplast - Skritaya sistema installyatsii dlya suxoy ustanovki', 277.35, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ10-750M.', 'Alcaplast APZ10 Simple Vodootvodyashchiy jelob s porogami dlya perforirovannoy reshetki 750 mm AG100401750', 232.96, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ13-DOUBLE9-650.', 'Alcaplast APZ13-DOUBLE9 Vodootvodyashchiy jelob s dvuxstoronney reshetkoy DOUBLE gorizontalniy stok, 650 mm AG071401650', 425.26, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ13-DOUBLE9-750.', 'Alcaplast APZ13-DOUBLE9 Vodootvodyashchiy jelob s dvuxstoronney reshetkoy DOUBLE gorizontalniy stok, 750 mm AG071401750', 337.50, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ13-DOUBLE9-850.', 'Alcaplast APZ13-DOUBLE9 Vodootvodyashchiy jelob s dvuxstoronney reshetkoy DOUBLE gorizontalniy stok, 850 mm AG071401850', 541.75, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ13-DOUBLE9-950.', 'Alcaplast APZ13-DOUBLE9 Vodootvodyashchiy jelob s dvuxstoronney reshetkoy DOUBLE gorizontalniy stok, 950 mm AG071401950', 580.57, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ2012-850.', 'Alcaplast APZ2012 Optimal Vodootvodyashchiy jelob s porogami dlya reshetki ili reshetki pod plitku, bez gidrozatvora 850 mm APZ2012-850', 110.94, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M1728-2.', 'Alcaplast Knopka.  Cherniy glyantseviy', 77.65, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M378.', 'Alcaplast Knopka. Cherniy glyantseviy', 88.75, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M678.', 'Alcaplast Knopka. cherniy matoviy', 77.65, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M371.', 'Alcaplast Knopka. Xrom glyantseviy', 68.41, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M372.', 'Alcaplast Knopka. Xrom matoviy', 88.75, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('AKS6.', 'Alcaplast Perexodnaya mufta HT 40/50 x G1/2', 22.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APS2.', 'Alcaplast Sifon dlya stiralnoy mashini narujniy beliy APS2', 16.64, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APS1.', 'Alcaplast Sifon dlya stiralnoy mashini narujniy xromirovanniy APS1', 20.34, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APS4.', 'Alcaplast Sifon dlya stiralnoy mashini pod shtukaturku beliy APS4', 22.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APS3.', 'Alcaplast Sifon dlya stiralnoy mashini pod shtukaturku xromirovanniy AG210321100', 22.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A 431.', 'Alcaplast Sifon dlya umivalnika ?32, tselnometallicheskiy, s nakidnoy gaykoy 5/4 A431', 55.48, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A 400.', 'Alcaplast Sifon dlya umivalnika, tselnometallicheskiy krugliy A400', 101.69, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A51VM.', 'Alcaplast Sifon dlya vanni avtomat komplekt beliy plastik/plastik dlina 57 sm', 55.48, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A51CR.', 'Alcaplast Sifon dlya vanni avtomat komplekt xromirovanniy plastik/metall dlina 57 sm A51CR', 98.00, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APV32BLACK.', 'Alcaplast Slivnoy trap 105?105/50 mm pryamoy stok SMART APV32BLACK', 38.82, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APV32.', 'Alcaplast Slivnoy trap primoy s gidrozatvorom', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M578.', 'Alcaplast THIN Knopka. cherniy matoviy', 77.65, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M57-G-M.', 'Alcaplast Thin Knopka. Zoloto matoviy', 107.24, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ23-DOUBLE9-950.', 'Alcaplast Vodootvodyashchiy jelob s dvuxstoronney reshetkoy DOUBLE gorizontalniy stok, 950 mm', 580.57, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ10BLACK-750M.', 'Alcaplast Vodootvodyashchiy jelob s porogami dlya perforirovannoy reshetki,cherniy-mat AG101101750', 290.27, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ20-850.', 'Alcaplast Vodootvodyashchiy jelob s porogami iz nerjaveyushchey stali dlya dvustoronney reshetki', 369.80, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ20-950.', 'Alcaplast Vodootvodyashchiy jelob s porogami iz nerjaveyushchey stali dlya dvustoronney reshetki', 462.24, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APZ20-750.', 'Alcaplast Vodootvodyashchiy jelob s porogami iz nerjaveyushchey stali dlya dvustoronney reshetki APZ20-750', 290.27, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APV240.', 'AlcaPlast. Slivnoy trap', 73.95, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APV140.', 'AlcaPlast. Slivnoy trap, dvuxstoronnyaya reshetka', 73.95, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('APV 31.', 'AlcaPlast. Trap.Bokovoy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('M0550MPSECOSTD', 'Ecosoft P''URE AquaCalcium obratniy osmos', 437.50, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('49560.', 'Koltsa. dlya shtangi komplekt 12sht s chyornimi sharikami', 27.74, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0243301.', 'Oporniy poruchen dlya vannoy', 18.49, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A 00130051.', 'Poruchen dlya vanni matoviy', 33.27, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A00145051.', 'Poruchen dlya vanni matoviy', 36.99, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A261100.', 'Poruchen dlya vanni S-obrazniy Art M xrom', 120.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A141100.', 'Ridder. Adapter XL dlya sidenya dlya dusha PRO, xrom, alyuminiy/PA/PE/TPR', 83.20, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('21107211.', 'Ridder. Derevyanniy kovrik Reshetka, ok. 38x72 sm, korichneviy, bambuk', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('21105211.', 'Ridder. Derevyanniy kovrik Reshetka, ok. 52x52 sm, korichneviy, bambuk', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('50600.', 'Ridder. Derjatel shtori', 18.49, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('49300.', 'Ridder. Koltsa dlya shtangi komplekt 12sht prozrachniy', 14.80, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('11117107.', 'Ridder. Korzina dlya belya Enna, seraya, s krishkoy, len/bambuk', 73.95, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('11118107.', 'Ridder. Korzina dlya belya Rica, seraya, len/bambuk', 73.95, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A162107.', 'Ridder. Kovrik dlya mitya nog s pemzoy Ease seriy PVX', 36.99, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('7102307.', 'RIDDER. Kovrik dlya vannoy komnati Carl seriy 60x90', 83.20, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('7021409.', 'Ridder. Kovrik. Fresh 60x90 Bejeviy', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('7021410.', 'Ridder. Kovrik. Fresh 60x90 Cherniy', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0110101.', 'Ridder. Mobilnoe prisposoblenie dlya obespecheniya dostupnosti tualeta Sam, beloe, vkl. lotok dlya xraneniya, stal / EVA', 221.88, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('49566.', 'Ridder. Nabor iz 12 kolets dlya shtorki', 27.74, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('11120110.', 'Ridder. Otdelno stoyashchiy polotentsesushitel Albany, cherniy matoviy, stal/bambuk', 184.89, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('608603.', 'Ridder. Podgolovnik dlya vanni', 9.25, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A173100.', 'Ridder. Podlokotniki dlya tabureta dlya vannoy Pro, xrom, alyuminiy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0102601.', 'Ridder. Podstavka dlya nog Sam, beliy, reguliruemaya po visote, polietilen/alyuminiy', 110.94, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0040101.', 'Ridder. Polka dlya vanni Sem, s ruchkoy, PE', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0014511.', 'Ridder. Poruchen Sam M, blestyashchiy xrom, s protivoskolzyashchey poverxnostyu, nerjaveyushchaya stal', 110.94, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0013011.', 'Ridder. Poruchen Sam S, blestyashchiy xrom, s protivoskolzyashchey poverxnostyu, nerjaveyushchaya stal', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A070110.', 'Ridder. Progulochnaya kolyaska Walker dlya pojilix lyudey ECO', 702.61, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('6001400.', 'Ridder. Protivoskolzyashchaya polosa Sicuro ok. 2x500 sm, poluprozrachniy, v rulone, 100% PEVA', 27.74, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A6800109.', 'Ridder. Protivoskolzyashchiy kovrik dlya vannoy TecnoPlus ok. 38x89 sm, bejeviy, SEBS', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A6800101.', 'Ridder. Protivoskolzyashchiy kovrik dlya vannoy TecnoPlus ok. 38x89 sm, beliy, SEBS', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A6800107.', 'Ridder. Protivoskolzyashchiy kovrik dlya vannoy TecnoPlus ok. 38x89 sm, seriy, SEBS', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A159101.', 'Ridder. Shchetka dlya dusha s dozatorom jidkogo mila. Dlina 475 mm', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('47337.', 'Ridder. Shtora dlya vannix komnat Cosmos beliy 180*200', 36.99, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('3101303.', 'RIDDER. Shtora dlya vannix komnat Oriental siniy/goluboy 180x200', 36.99, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('4108300.', 'Ridder. Shtora dlya vannoy Elephant 180x200 v sovremennom stile', 64.71, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A180101.', 'Ridder. Sidene dlya vanni Pro, beliy, alyuminiy/PA/TPR', 166.40, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A130000.', 'RIDDER. Skladnie rollatori ASSISTANT - chernie', 739.57, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A140110.', 'Ridder. Skladnoe sidene dlya dusha Pro, cherniy, PA/alyuminiy', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A140108.', 'Ridder. Skladnoe sidene dlya dusha Pro, priroda, bambuk/alyuminiy', 184.89, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A140107.', 'Ridder. Skladnoe sidene dlya dusha Pro, seriy, PA/alyuminiy', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A00300101.', 'Ridder. Sredstva obespecheniya dostupnosti dlya vann Sam, beliy, PP/TPE/Alyuminiy', 138.67, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A00602101.', 'Ridder. Stul dlya vannoy Sam, beliy, reguliruemiy po visote, polietilen/alyuminiy', 184.89, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A170101.', 'Ridder. Taburet dlya vannoy Go, beliy, reguliruemiy po visote, alyuminiy/PE/TPR', 120.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A170110.', 'Ridder. Taburet dlya vannoy Go, cherniy, reguliruemiy po visote, alyuminiy/PE/TPR', 120.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A170117.', 'Ridder. Taburet dlya vannoy Go, seriy, reguliruemiy po visote, alyuminiy/PE/TPR', 120.19, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0050401.', 'Ridder. Taburet dlya vannoy Ole, beliy, reguliruetsya po visote, povorotnoe sidene, PP/PU/alyuminiy', 184.89, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A172101.', 'Ridder. Taburet dlya vannoy Pro, beliy, s regulirovkoy po visote, alyuminiy / PA / TPR / PE / PP', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A172110.', 'Ridder. Taburet dlya vannoy Pro, cherniy, reguliruetsya po visote alyuminiy / PA / TPR / PE / PP', 147.92, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A172108.', 'Ridder. Taburet dlya vannoy Pro, naturalniy, s reguliruemoy visotoy, alyuminiy/TPR/PE/PP/bambuk', 184.89, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0050501.', 'Ridder. Taburet dlya vannoy Sam, beliy, s gigienicheskim virezom, reguliruemiy po visote, PE/alyuminiy', 129.43, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A00603101.', 'Ridder. Taburet dlya vannoy Ted, beliy, reguliruemiy po visote, PP/alyuminiy', 92.45, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A211110.', 'Ridder. Taburet dlya vannoy Trendy, cherniy matoviy, akril', 369.80, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A171101.', 'Ridder. Taburet v vannu Pro beliy Assistent', 129.43, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A1102601.', 'Ridder. Taburet v vannu Promo 40 sm beliy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A1102614.', 'Ridder. Taburet v vannu Promo 40 sm oranjeviy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A1102613.', 'Ridder. Taburet v vannu Promo 40 sm rozoviy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A1102607.', 'Ridder. Taburet v vannu Promo 40 sm seriy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A1102603.', 'Ridder. Taburet v vannu Promo 40 sm siniy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A1102605.', 'Ridder. Taburet v vannu Promo 40 sm zelyoniy', 46.21, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('4104307.', 'Shtora dlya vanni', 18.49, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('48301.', 'Shtora dlya vannix komnat Diamond beliy 180*200', 33.27, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('4105307.', 'Shtorka dlya vanni Ridder Toscana', 29.57, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0102001.', 'Skameyka-lestnitsa dlya vannoy', 166.40, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A0120101.', 'Stul dlya vannoy komnati', 173.80, 'dona', 'SANTEXNIKA', 'ALCAPLAST'),
  ('A00502081.', 'Taburet v vannuyu RIDDER Assistent s reguliruemoy visotoy, A00502081, bambuk/matoviy xrom', 314.32, 'dona', 'SANTEXNIKA', 'ALCAPLAST')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- AVTOMATIKA / CLIMATE HOUSE  (1 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('BHT-008GBLW', 'Termoregulyator upravleniya dlya trexxodovogo krana', 100.00, 'dona', 'AVTOMATIKA', 'CLIMATE HOUSE')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- AVTOMATIKA / DANFOSS  (2 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('088U0622', 'Danfoss komnatniy termostat', 62.50, 'dona', 'AVTOMATIKA', 'DANFOSS'),
  ('088U0610', 'Danfoss zont dlya pola', 13.20, 'dona', 'AVTOMATIKA', 'DANFOSS')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- AVTOMATIKA / Neptun  (23 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('Neptun 20.', 'Datchik kontrolya protechki vodi SW005', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 21.', 'Datchik kontrolya protechki vodi SW007', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 23.', 'Istochnik bespereboynogo pitaniya 18650 (12V)', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 7.', 'Kran s elektroprivodom Neptun Bugatti Pro 220V 1', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 8.', 'Kran s elektroprivodom Neptun Bugatti Pro 220V 1 1/2', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 5.', 'Kran s elektroprivodom Neptun Bugatti Pro 220V 1/2', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 9.', 'Kran s elektroprivodom Neptun Bugatti Pro 220V 2', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 6.', 'Kran s elektroprivodom Neptun Bugatti Pro 220V 3/4', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 16.', 'Kran s elektroprivodom Neptun PROFI 12V 1', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 17.', 'Kran s elektroprivodom Neptun PROFI 12V 1 1/4', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 14.', 'Kran s elektroprivodom Neptun PROFI 12V 1/2', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 15.', 'Kran s elektroprivodom Neptun PROFI 12V 3/4', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 12.', 'Kran s elektroprivodom Neptun PROFI 220V 1', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 13.', 'Kran s elektroprivodom Neptun PROFI 220V 1 1/4', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 10.', 'Kran s elektroprivodom Neptun PROFI 220V 1/2', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 11.', 'Kran s elektroprivodom Neptun PROFI 220V 3/4', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 18.', 'Modul upravleniya Neptun Base', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 19.', 'Modul upravleniya Neptun Smart+ (TUYA)', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 22.', 'Radiodatchik Neptun Smart 868', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 1.', 'Sistema Neptun Aquacontrol 1/2 (komplekt)', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 2.', 'Sistema Neptun Aquacontrol 3/4 (komplekt)', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 3.', 'Sistema Neptun PROFI Base 3/4 (komplekt)', 1.00, 'dona', 'AVTOMATIKA', 'Neptun'),
  ('Neptun 4.', 'Sistema Neptun Profi Smart+ 3/4 (TUYA) (komplekt)', 1.00, 'dona', 'AVTOMATIKA', 'Neptun')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


-- AVTOMATIKA / Smartheat  (61 ta)
insert into hs_products (artikul, nomi, narx, birlik, kategoriya, kichik_kategoriya) values
  ('AE-668-3A-Golden.', 'SmartHeat AE-668-3A-Golden Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 50.00, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-668D-3A-Silver.', 'SmartHeat AE-668D-3A-Silver Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 50.00, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-668D-3A-White.', 'SmartHeat AE-668D-3A-White Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 50.00, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-669D-3A-Black.', 'SmartHeat AE-669D-3A-Black Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 51.56, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-669Dual1black.', 'SmartHeat AE-669Dual1black Dvuxkanalniy termostat (2 klapana, 3A, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-669Dual1white.', 'SmartHeat AE-669Dual1white Dvuxkanalniy termostat (2 klapana, 3A, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-669S-3A-White.', 'SmartHeat AE-669S-3A-White Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 50.00, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-T7S.', 'SmartHeat AE-T7S Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 31.25, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE-T7SBLACK.', 'SmartHeat AE-T7SBLACK Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 31.25, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE550316A BLACK.', 'SmartHeat AE550316A BLACK Termostat (16A, magnitniy korpus, Wi-Fi)', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE550316A WHITE.', 'SmartHeat AE550316A WHITE Termostat (16A, magnitniy korpus, Wi-Fi)', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE5503DUALBLACK.', 'SmartHeat AE5503DUALBLACK Dvuxkanalniy termostat (2 klapana, magnitniy korpus, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE5503DUALWHITE.', 'SmartHeat AE5503DUALWHITE Dvuxkanalniy termostat (2 klapana, magnitniy korpus, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE720 BLACK.', 'SmartHeat AE720 BLACK Dvuxkanalniy termostat (2 klapana, nagrev vodi 3A, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('AE720 WHITE.', 'SmartHeat AE720 WHITE Dvuxkanalniy termostat (2 klapana, nagrev vodi 3A, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BAC006BLACK.', 'SmartHeat BAC006BLACK Termostat dlya konvektora 24V (nagrev/oxlajdenie, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BAC006BLACK230.', 'SmartHeat BAC006BLACK230 Termostat dlya konvektora 230V (nagrev/oxlajdenie, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BAC006EL BLACK.', 'SmartHeat BAC006EL BLACK Termostat dlya FAN COIL 95-240V (3 skorosti vent., Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BAC006EL WHITE.', 'SmartHeat BAC006EL WHITE Termostat dlya FAN COIL 95-240V (3 skorosti vent., Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BAC00WHITE.', 'SmartHeat BAC00WHITE Termostat dlya konvektora 24V (nagrev/oxlajdenie, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BAC00WHITE230.', 'SmartHeat BAC00WHITE230 Termostat dlya konvektora 230V (nagrev/oxlajdenie, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BHTBLACK.', 'SmartHeat BHTBLACK Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi)', 40.62, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BHTRFBLACK.', 'SmartHeat BHTRFBLACK Besprovodnoy termostat (nagrev vodi 3A, Wi-Fi)', 101.56, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BHTRFWHITE.', 'SmartHeat BHTRFWHITE Besprovodnoy termostat (nagrev vodi 3A, Wi-Fi)', 101.56, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('BHTWHITE.', 'SmartHeat BHTWHITE Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi)', 40.62, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Sensor NTC.', 'SmartHeat Datchik temperaturi teplogo pola NTC 10kOm, 3m, IP25', 4.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 230V M30 NC (ruchnoy).', 'SmartHeat Dvuxpoz. servoprivod NC 230V AC M30x1.5mm (ruchnoy rejim)', 12.50, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 230V M30 NO (tsvet.ind).', 'SmartHeat Dvuxpoz. servoprivod NC 230V AC M30x1.5mm (ruchnoy rejim, tsvet.ind)', 12.50, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('FCU & FL BLACK.', 'SmartHeat FCU & FL BLACK Dvuxkanalniy termostat 24V (2 klapana, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('FCU & FL WHITE.', 'SmartHeat FCU & FL WHITE Dvuxkanalniy termostat 24V (2 klapana, Wi-Fi)', 70.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('HY09 RF BW.', 'SmartHeat HY09 RF BW Besprovodnoy termostat (nagrev kotla 3A, Wi-Fi)', 78.12, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('HY520.', 'SmartHeat HY520 Kommutatsionnaya panel 230V, 8 kanalov, 16 privodov', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('HY609AC24vBLACK.', 'SmartHeat HY609AC24vBLACK Termostat dlya konvektora 95-240V (0-10V, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('HY609C240v.', 'SmartHeat HY609C240v Termostat dlya konvektora 95-240V (0-10V, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('HY609C24v.', 'SmartHeat HY609C24v Termostat dlya konvektora 24V (0-10V, Wi-Fi)', 59.38, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('M1 Black+White.', 'SmartHeat M1 Black+White Smart Thermostat (nagrev vodi 3A)', 28.12, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('M2 Black.', 'SmartHeat M2 Black Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('M2 White.', 'SmartHeat M2 White Smart Thermostat (nagrev vodi 3A, Wi-Fi)', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('M3HBLACK.', 'SmartHeat M3HBLACK Komnatniy termostat glansoviy (nagrev vodi 3A, Wi-Fi)', 39.06, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('M3HWHITE.', 'SmartHeat M3HWHITE Komnatniy termostat glansoviy (nagrev vodi 3A, Wi-Fi)', 39.06, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('ME80B WIFI.', 'SmartHeat ME80B WIFI Smart Thermostat Premium (nagrev vodi 3A, Wi-Fi)', 73.44, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('MH008BlACK.', 'SmartHeat MH008BLACK Termostat (16A, Wi-Fi)', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('MH008WHITE.', 'SmartHeat MH008WHITE Termostat (16A, Wi-Fi)', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('O3-GA-B.', 'SmartHeat O3-GA-B Komnatniy termostat matoviy (nagrev vodi 3A, Wi-Fi)', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('O3-GA-W.', 'SmartHeat O3-GA-W Komnatniy termostat matoviy (nagrev vodi 3A, Wi-Fi)', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('R-2.', 'SmartHeat R-2 Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi, Uzb/Rus/Eng)', 78.12, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('S-006.', 'SmartHeat S-006 Universalniy termostat dlya NC servoprivodov (16A, Wi-Fi)', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('S-007.', 'SmartHeat S-007 Universalniy termostat dlya NC servoprivodov (16A, Wi-Fi)', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('SAS965FHL.', 'SmartHeat SAS965FHL Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi, Rus/Eng)', 78.12, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo ONE 220V M30 NC.', 'SmartHeat Servoprivod ONE NC 220V M30x1.5mm', 8.31, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 230V M30 NC (bazoviy).', 'SmartHeat Servoprivod termoelektricheskiy NC 230V AC M30x1.5mm (5 let garantiya)', 15.62, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 230V M30 NC (tsvet.ind).', 'SmartHeat Servoprivod termoelektricheskiy NC 230V AC M30x1.5mm (tsvetnoy indikator)', 12.50, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 24V M30 NC.', 'SmartHeat Servoprivod termoelektricheskiy NC 24V AC M30x1.5mm (5 let garantiya)', 15.62, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 24V M30 NC (std).', 'SmartHeat Servoprivod termoelektricheskiy NC 24V M30x1.5mm', 12.50, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 230V M30 NO.', 'SmartHeat Servoprivod termoelektricheskiy NO 230V AC M30x1.5mm', 12.50, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('Servo 24V M30 NO.', 'SmartHeat Servoprivod termoelektricheskiy NO 24V M30x1.5mm', 12.50, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('TH2160 BLACK.', 'SmartHeat TH2160 BLACK Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi)', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('TH2160 WHITE.', 'SmartHeat TH2160 WHITE Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi)', 54.69, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('TPX05.', 'SmartHeat TPX05 Kommutatsionnaya panel 230V, 5 kanalov, 10 privodov', 42.19, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('TPX08.', 'SmartHeat TPX08 Kommutatsionnaya panel 230V, 8 kanalov, 16 privodov', 46.88, 'dona', 'AVTOMATIKA', 'Smartheat'),
  ('WT20R.', 'SmartHeat WT20R Smart Thermostat Premium (nagrev vodi 5A, Wi-Fi)', 56.25, 'dona', 'AVTOMATIKA', 'Smartheat')
on conflict (artikul) where artikul <> '' do update
  set nomi = excluded.nomi, narx = excluded.narx,
      kategoriya = excluded.kategoriya, kichik_kategoriya = excluded.kichik_kategoriya,
      faol = true;


notify pgrst, 'reload schema';

select count(*) as shu_bolakda from hs_products where (kategoriya, coalesce(kichik_kategoriya,'')) in (
  ('DIMAXOD', 'A.D.M'),
  ('DIMAXOD', 'COX GEELEN'),
  ('IZOLYATSIYA', 'ENERGOFLEX'),
  ('IZOLYATSIYA', 'TONLOS'),
  ('KATYOL', ''),
  ('SANTEXNIKA', 'ALCAPLAST'),
  ('AVTOMATIKA', 'CLIMATE HOUSE'),
  ('AVTOMATIKA', 'DANFOSS'),
  ('AVTOMATIKA', 'Neptun'),
  ('AVTOMATIKA', 'Smartheat')
);
